### ISSUE TITLE
~~~

### ISSUE THREAD

**Issue by Kissying** [stiekel/hexo-theme-random#1]
整体大赞
如何隐藏掉 左下的hide按钮？另外如何让 背景图取自bing那样一天换一张而不是一直轮换？

**Comment by stiekel** [comment]
谢谢你喜欢。

hide捥现在不能隐藏，我今天加上。

一天一轮换的，这个得单独加。我还得想想怎么做。

**Comment by stiekel** [comment]
1. 隐藏 Hide 按钮的配置已经加上，在 Hexo 主配置文件或者 Random 的主题配置文件中，增加一个 `hideButtonVisibility` ，并设置为 false 即可
2. 关于背景的问题，毕竟这个主题的名字就是 Random ，想的就是背景随机显示和切换，所以我可能不准备增加这种一天一换的功能了。如果你需要，可以考虑做个自定义，具体你可以看一下主题目录中 `source/js/rando.js` 的脚本，修改一下 `vegasConfig.slides = slides;` 这一行中 `slides` 的来源即可
