### ISSUE TITLE
单行代码过长可以显示横向滚动条

### ISSUE THREAD

**Issue by tripleday** [stiekel/hexo-theme-random#10]
生成的博客会有点尴尬。
![y 59k vdaa hab lvi 8](https://cloud.githubusercontent.com/assets/16516510/16440474/cf056ab0-3df4-11e6-9a75-8ce12224487c.png)

**Comment by stiekel** [comment]
默认是有的，具体可以看这个文章： http://chensd.com/2015-03/AngularJS-ngOptions-ngRepeat-filter-exclude-and-screen.html 这里的最后一段代码，是有水平滚动条的。

我看了一下你的说的问题，应该是 http://tripleday.github.io/2016/06/16/centos&scrapy&ghost.py/ ，我看这文章的源文件中，使用的是三个 ` 来标明开始代码的，但没有指定是代码语言，所以默认为普通文本。你可以用 ````sh` 来指定是普通命令。这样就会有对应的高亮和滚动条。

我会给普通文本的代码段加一个水平滚动条。

**Comment by tripleday** [comment]
谢谢解释
