### ISSUE TITLE
关于网站标题

### ISSUE THREAD

**Issue by JayceCao** [stiekel/hexo-theme-random#11]
根据我的测试，主配置文件中sub-title的值会和网页名一同显示在网页的标题上面，但是decription的值不会显示在主页的title下面，能不能让description的值显示在主页title下面。。。

**Comment by stiekel** [comment]
您好，description 的值，的确是不会显示在那里的。如果你的确想这样显示，可以在修改 [themes/random/layout/index.swig 的第 9 行](https://github.com/stiekel/hexo-theme-random/blob/master/layout/index.swig#L9)，将 `config.subtitle` 改为 `config.description` 即可。

**Comment by JayceCao** [comment]
搞定啦！谢谢了！还有一个问题。。。就是正文部分的背景颜色和透明度在哪儿设置呀。。。

**Comment by stiekel** [comment]
可以修改 id 为 container 的元素的透明度即可。

**Comment by JayceCao** [comment]
如果是修改已经部署好的网页的话，下一次重新部署的时候会不会覆盖掉？如果覆盖掉的话，能不能从配置中增加修改选项？

**Comment by JayceCao** [comment]
自己动手搞定了0.0 打扰了！

**Comment by stiekel** [comment]
只要是改的 Hexo 的主题代码，下次重新部署，不会没有的。
