### ISSUE TITLE
abouts 列表列怎么创建

### ISSUE THREAD

**Issue by Engineering-Course** [stiekel/hexo-theme-random#12]
根据文档的方法 创建了tags和categories列表  用同样的方法创建abouts不可行 请问怎么创建about？

**Comment by Engineering-Course** [comment]
I used 
hexo new page about
and solved the problem.
for I used wrong command befor:
hexo new page abouts

**Comment by stiekel** [comment]
about 页没有专门的代码，使用 `hexo new page about` 创建后，自行规划即可。
