### ISSUE TITLE
jiathis 显示

### ISSUE THREAD

**Issue by Engineering-Course** [stiekel/hexo-theme-random#13]
配置了jiathis之后  分享栏在哪里显示？

**Comment by stiekel** [comment]
会在文章内容页显示在侧边。明天我给你截图演示。

**Comment by stiekel** [comment]
刚刚发现，有个 jiaThis 的变量名有问题，已经在 a5b148a2134d526d75760cd77ed866814ece15bd 中修正。
配置代码在 `_config.yml` 的[第34至40行](https://github.com/stiekel/hexo-theme-random/blob/master/_config.yml#L33)，效果如下：

![jiaThis on Random](http://i.imgur.com/HUYHNoD.png)

**Comment by Engineering-Course** [comment]
inserted the jiaThis_uid and refined the problem in jiathis.swig. I still can't find jiathis share frame
any other places should I modify?

I inserted the jiaThis_uid like this:
jiaThis_uid: 21***33

**Comment by stiekel** [comment]
Would you please commit and push your,code to Github?

**Comment by Engineering-Course** [comment]
Yes. The code has already been pushed.
[Hexo project code](https://github.com/Engineering-Course/blog)
[generated blog code](https://github.com/Engineering-Course/Engineering-Course.github.io)

**Comment by stiekel** [comment]
hi, I clone you code from the repository and run it, and I got the jiaThis run currently.

BTW, the jiaThis only show on post detail page, beside the Table of Content.

![jiaThis on Clay's Blog](http://i.imgur.com/yjREfXs.png)

**Comment by stiekel** [comment]
@Engineering-Course I checked the code that generated by Hexo of your blog repository, and I found the jiaThis code, like [1](https://github.com/Engineering-Course/Engineering-Course.github.io/blob/5eb41fe8972d68f7bf6a894daae080147196de0a/2016/07/07/new-article/index.html#L148), [2](https://github.com/Engineering-Course/Engineering-Course.github.io/blob/5eb41fe8972d68f7bf6a894daae080147196de0a/about/index.html#L124), [3](https://github.com/Engineering-Course/Engineering-Course.github.io/blob/5eb41fe8972d68f7bf6a894daae080147196de0a/2016/07/09/hello-world/index.html#L158).

**Comment by Engineering-Course** [comment]
![image](https://cloud.githubusercontent.com/assets/7713394/16726664/00c25fc8-4790-11e6-9712-7c232bcb018d.png)
I found an error when I checked the sources of the page. Is it the reason for my problem?

**Comment by stiekel** [comment]
Because you are use https, and load jiaThis script from over http. I will fix this issue before tomorrow.

**Comment by stiekel** [comment]
Bug fixed, please pull commit 0b4edfbfdd28cb256df50e9873d6ab325f62c294 .

**Comment by Engineering-Course** [comment]
Thank you.
But unfortunately, another error comes out.
![image](https://cloud.githubusercontent.com/assets/7713394/16765407/73e88a14-4866-11e6-8e82-3356a8fa6524.png)

And I also confused why you could set up my repository and get jiaThis successfully but I always failed.

**Comment by stiekel** [comment]
The  jiaThis script didnot served by https.
you can download the script file to your local folder.

**Comment by Engineering-Course** [comment]
But your blog is also based on https, isn't it?

**Comment by Engineering-Course** [comment]
So, which jiathis js file should I download, and put them to which folder, please?

**Comment by stiekel** [comment]
The second url in this image:
![error load jiaThis script over https](https://cloud.githubusercontent.com/assets/7713394/16726664/00c25fc8-4790-11e6-9712-7c232bcb018d.png)

**Comment by stiekel** [comment]
My blog was hosted at [Coding Pages](https://coding.net/help/doc/pages/) over http.
