### ISSUE TITLE
关于markdown语法之引用

### ISSUE THREAD

**Issue by JayceCao** [stiekel/hexo-theme-random#14]
模板对于引用的渲染貌似只是将内容放在了<p>标签之内。可以稍微加一点修饰，比如前面加个竖线什么的，使得和普通文本更易于区分

**Comment by stiekel** [comment]
好的，谢谢建议，我这周将这个修改做出来。

**Comment by stiekel** [comment]
已经添加样式，参见 3331deae100945f0e69a26e73a0ef970680976d9 。

**Comment by stiekel** [comment]
你如果想制作 Hexo 主题，正好我这里有篇基于本主题写的一个教程，参见： http://chensd.com/2016-06/hexo-theme-guide.html 。

奇怪，我在 ForkHub 上看到你在 3331dea 上提交了一个评论，但实际上却没有。

**Comment by JayceCao** [comment]
啊。。。那个评论是原本是有的，但是发现写错地方了。。。就撤回了。。。好的，这周学习一下。
