### ISSUE TITLE
关于rss

### ISSUE THREAD

**Issue by JayceCao** [stiekel/hexo-theme-random#15]
希望可以添加rss订阅功能恩。。。

**Comment by JayceCao** [comment]
增加一个rss的图标

**Comment by stiekel** [comment]
好的，我这周来实现。

**Comment by stiekel** [comment]
RSS 图标已经添加，文档也已经更新，请参见 [添加 RSS 图标](https://github.com/stiekel/hexo-theme-random/blob/master/README.CN.md#添加-rss-图标) 。
