### ISSUE TITLE
代码支持多行吗

### ISSUE THREAD

**Issue by sunzongzheng** [stiekel/hexo-theme-random#17]
请问code是不是不支持多行？

**Comment by stiekel** [comment]
支持多行的，但需要指定语言，比如：使用
> \`\`\`js
> \`\`\`
来包裹代码。

**Comment by stiekel** [comment]
已经解决了，当没有指定语言的时候，使用原格式组织格式。

**Comment by sunzongzheng** [comment]
嗯，测试了一下确实可以了。行号好像还有一点点问题，兄弟你可以测试一下...图传不上来...
```js
		cd /usr/local/src

		wget https://github.com/alibaba/nginx-http-concat/archive/master.zip -O nginx-http-concat-master.zip

		unzip nginx-http-concat-master.zip
	```

**Comment by stiekel** [comment]
行号没办法了，你只能通过指定语言来实现。你这个是 shell ，所以，不要指定 js 要指定 sh。

**Comment by stiekel** [comment]
github 中贴图，必须是先传图床再用地址的方式加进来。
具体代码格式这夫儿，请参考这里的样例：
https://raw.githubusercontent.com/stiekel/blog/master/source/_posts/Authorzation-and-Login-in-Angular.md

**Comment by sunzongzheng** [comment]
oo，好，thanks
