### ISSUE TITLE
怎么给一篇文章加上多个标签

### ISSUE THREAD

**Issue by Wonder233** [stiekel/hexo-theme-random#19]
我试了在md文件中的很多种加标签的方法，但是都没有成功
tags: hexo/makedown  这个到底是怎样分隔多个标签的呀？

**Comment by stiekel** [comment]
方法见这里： https://raw.githubusercontent.com/stiekel/blog/master/source/_posts/Safe-username-password-Login-System.md

**Comment by Wonder233** [comment]
谢谢~~  明白了
