### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by SummerHF** [stiekel/hexo-theme-random#2]
i can't change the avatar ,even i have set it (incluing hexo main config file and theme config ),but it always shows ,"http://7te9fe.com1.z0.glb.clouddn.com/default_avatar.jpg".it is awful........... then i removed the avatar in the theme config, it's not useful too. it confuses me,i need your help............thanks

**Comment by SummerHF** [comment]
首页的图像就是换不掉 但是其他的页面的头像都换掉了 什么鬼啊

**Comment by stiekel** [comment]
回复了 issue #3

**Comment by SummerHF** [comment]
it works  thanks

**Comment by stiekel** [comment]
😄

**Comment by SummerHF** [comment]
哥们 能加个简书的么 😀

**Comment by stiekel** [comment]
抱歉朋友，我简书上没东西。谢谢你。

**Comment by SummerHF** [comment]
HAODE
