### ISSUE TITLE
添加Instagram图标吧。

### ISSUE THREAD

**Issue by seon212** [stiekel/hexo-theme-random#20]
如题（虽然大陆地区访问不了但还是希望添加，或者添加Instagram页面。）

**Comment by luran2358** [comment]
可以添加简书和稀土掘金 的图标吗

**Comment by stiekel** [comment]
@luran2358 @seon212 Instagram 和 简书的 icon 已经添加了。但稀土掘金的 icon 在 iconfont.cn 上还没有，所以没有添加。参见 109943022b6f9f014a844c6568b41f3a0572a764 。
