### ISSUE TITLE
WARN No Layout: index.html

### ISSUE THREAD

**Issue by pawndev** [stiekel/hexo-theme-random#21]
Hi everyone,
I'm here because i met a problem today, when i use this theme and i launch hexo server locally, all is goo

But when i run hexo server on heroku i receive "WARN No Layout: index.html" in the log

Thanks for your help

(sorry for my english, I'm french)

**Comment by stiekel** [comment]
It doesn't matter, and I am not good at English too.
I had deployed the [demo](http://hexo-theme-random.herokuapp.com/) on heroku, It's works, and the [index.html](http://hexo-theme-random.herokuapp.com/index.html) , please ignore the warning message, or you can give me the full log, we may can find the answer.
