### ISSUE TITLE
建议增加微信和qq的社交图标，网站标题

### ISSUE THREAD

**Issue by ReinhardHsu** [stiekel/hexo-theme-random#22]
毕竟，这两个还是主流社交工具。
网站标题用[ ]是不是有点另类了？我把标题这部分做了点修改，大家可以参考下。

{% set pageTitle = page.title || '' %}
{% if is_archive() %}
  {% set pageTitle = _p('archive_title') %}
{% endif %}
{% if is_tag() %}
  {% set pageTitle = __('tag_title') + ': ' + page.tag %}
{% endif %}
{% if is_category() %}
  {% set pageTitle = __('category_title') + ': ' + page.category %}
{% endif %}
{% if is_month() %}
  {% set pageTitle = pageTitle + ': ' + page.month + '/' + page.year %}
{% endif %}
{% if is_year() %}
  {% set pageTitle = pageTitle + ': ' + page.year %}
{% endif %}
{% if pageTitle.length <1 %}
  {% set pageTitle = config.title + ' - ' + config.subtitle %}
{% else %}
  {% set pageTitle = pageTitle + ' - ' + config.title %}
{% endif %}

**Comment by stiekel** [comment]
哈哈，的确，我也是觉得 [] 有点儿不大好。
