### ISSUE TITLE
建议增加segmentfault和stackoverflow的图标

### ISSUE THREAD

**Issue by jasminecjc** [stiekel/hexo-theme-random#24]
如题，作为程序猿，觉得别人在看博客的时候会希望看到这两个网站的相关信息

**Comment by stiekel** [comment]
好的，没问题。刚刚在 iconfont.cn 上看了一下，这两个网站都有对应的图标，我明天加一下。

**Comment by stiekel** [comment]
已经在 e1f10b99aeb5874994f854b444c54b86e281e302 中增加了相应的图标。

**Comment by yizuochengchi** [comment]
请教一下 我在主题配置里面 添加了友言 id 怎么文章没有出现评论框呢？谢谢

**Comment by stiekel** [comment]
@yizuochengchi 我这周末找时间看看啊。悲剧的多说。

**Comment by stiekel** [comment]
@yizuochengchi 测试了一下，在 hexo 的主配置文件 _config.yml 中增加 uyan_id 后，可以正常显示。你再检查一下，看是不是拼写有问题，我的配置如下：

```yml
uyan_id: 206xxxxx
```

**Comment by yizuochengchi** [comment]
好的 谢谢~
