### ISSUE TITLE
.

### ISSUE THREAD

**Issue by SummerHF** [stiekel/hexo-theme-random#3]
这个首页的头像太丑了 换又换不掉 真是败笔

**Comment by stiekel** [comment]
不好意思，是代码的问题，下午我来改掉。
你也可以直接在主题的 layout/index.swig 中去改。

**Comment by stiekel** [comment]
问题已经修复。可以通过以下方式更新：
1、进入你的 themes/random 目录，然后执行 git pull
2、如果第一步无法完成，可以直接编辑 `theme/random/layout/index.swig` 第15 行，具体请参见[这里](https://github.com/stiekel/hexo-theme-random/blob/master/layout/index.swig#L5)。
