### ISSUE TITLE
能否告诉我为什么我的代码高亮出现bug

### ISSUE THREAD

**Issue by songtoy** [stiekel/hexo-theme-random#32]
所有注释以下的代码均被高亮成了和注释一样的格式。

**Comment by stiekel** [comment]
可能是 markdown 的代码格式问题。

请参考这里的方式来在 markdown 中标记代码：
https://raw.githubusercontent.com/stiekel/blog/master/source/_posts/45-useful-javascript-tips-tricks-and-best-practices.md

**Comment by stiekel** [comment]
@songtoy  不知道你是不是指代码行号与当行代码对不齐的问题，如果是这个，现在已经在 5a55a05 里解决了。你可以更新一下你的主题文件试试。

**Comment by songtoy** [comment]
虽然有很长一段时间没用博客了，但还是非常感谢！
