### ISSUE TITLE
你好 请问怎么添加友言 评论？ 

### ISSUE THREAD

**Issue by yizuochengchi** [stiekel/hexo-theme-random#33]
<div id="uyan_frame"></div>
<script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=2129113"></script>
  在文章部分加了 怎么不显示？ 预览 是正常的 线上部署不显示。 谢谢

**Comment by stiekel** [comment]
直接在 hexo 的主配置文件中，增加 uyan_id 配置即可，如下：
```yml
uyan_id: 206xxxx
```

**Comment by prosscode** [comment]
添加uyan_id，实测并没有显示。

**Comment by stiekel** [comment]
@prosscode 可以把我的站点的 repo 发我看看吗

**Comment by prosscode** [comment]
@stiekel 
友言ID截图：
![image](https://user-images.githubusercontent.com/26180481/38535611-e2532946-3cb6-11e8-8dfd-dc107719cfda.png)
主题站点配置：
![image](https://user-images.githubusercontent.com/26180481/38535756-b763e8aa-3cb7-11e8-8471-eb9fe9ae1697.png)
博客效果：http://pross.space/2018/LeetCode-Palindrome-Number-9/

**Comment by stiekel** [comment]
@prosscode 我刚刚测试了一下，是可以的，就是使用你提供的 id 
![image](https://user-images.githubusercontent.com/2735087/38728957-f258b664-3f43-11e8-8cb0-d78c5e925298.png)

**Comment by prosscode** [comment]
@stiekel  是的，直接添加有效。
是我配置的问题。全局_config.yml配置中关闭了评论。
