### ISSUE TITLE
头像设置为题

### ISSUE THREAD

**Issue by HELOBILLY** [stiekel/hexo-theme-random#36]
您好，我想问一下关于头像设置的问题，在源主题中，头像的设置是avatar: http://7te9fe.com1.z0.glb.clouddn.com/default_avatar.jpg，在其他页面的左上角，也可以显示出来，但是如果我设置为自己的头像（如：avatar: zk.JPG），就只能在home页面中显示，而在其他的页面中（左上角）显示不出来，请问一下这个问题应该怎么解决呢？

**Comment by stiekel** [comment]
可能是相对路径的问题。
你在其它页面中，看看图片的引用地址（src）是什么。

**Comment by HELOBILLY** [comment]
嗯嗯，好的，谢谢您
