### ISSUE TITLE
关于如何修改底部powerby的问题

### ISSUE THREAD

**Issue by yuerenge** [stiekel/hexo-theme-random#38]
页面底部如何自定义配置？

**Comment by stiekel** [comment]
可以通过修改 [layout/includes/layout.swig](https://github.com/stiekel/hexo-theme-random/blob/5a55a05cc4a3dd37ca1314925d0be7dd9abf224e/layout/includes/layout.swig#L51) 来实现。

不过，如果只是修改名字，可以通过配置文件的 `author` 项来实现。
