### ISSUE TITLE
你好，关于文章里面的目录框的大小和文章顶部的导航菜单能否调整下宽高呢？

### ISSUE THREAD

**Issue by XinglongGuo** [stiekel/hexo-theme-random#39]
![image](https://user-images.githubusercontent.com/29576629/27725336-6b0cd4f6-5da8-11e7-85c0-7289fc799b7d.png)
>希望能调整下，看起来会比较美观。

**Comment by stiekel** [comment]
@XinglongGuo 目录是浮在最上层的，并不是在右边，因为不同的屏幕宽度是不一样的。

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
