### ISSUE TITLE
social icon

### ISSUE THREAD

**Issue by tang-yue** [stiekel/hexo-theme-random#4]
知乎图标不在其中，怎么办？

如何把首页菜单，即大写的 "ARCHIVES"  "TAGS" "CATEGORIES"  "ABOUT" 改成中文?以及博客主页里的菜单，即  "Home" “Archives” "Tags" "Categories" "About"改成中文?我把已经添加menu属性在路径themes/random/languages/里的zh-CN文件。
如下添加：
menu:
 home: 首页
 archives: 归档
 categories:分类
 tags: 标签
 about: 关于我
但是没有效果。

**Comment by stiekel** [comment]
*  知乎的我这几天加上
* 菜单请在主题或者主配置文件中添加相应的配置，参见[文档](https://github.com/stiekel/hexo-theme-random/blob/master/README.CN.md#菜单与导航链接的设置)，比如，在Hexo主配置文件（_config.yml）中修改：

```yml
menu:
  首页: /
  文章: /archives
  标签: /tags
  分类: /categories
  关于: /about
```

**Comment by stiekel** [comment]
zhihu的图标已经加好了，具体参见提交 f0427af6ad209d09cb80c1e1e4de98212c1772c3 。
建议把主题的全部文件更新一下，实在不想得话，更新如下文件：
* `themes/random/source/css/iconfont/` 下五个文件
* `themes/random/source/css/random.styl`
* `themes/random/layout/includes/social-icon.swig`

**Comment by tang-yue** [comment]
谢谢，都已经实现了，不好意思这么迟才回复你。
