### ISSUE TITLE
如何更换背景图源，而不是逐张图片添加

### ISSUE THREAD

**Issue by liyujx** [stiekel/hexo-theme-random#42]
怎样才能把默认的背景图源unsplash更换为其他源，例如必应随机图片，而不是逐张图片添加。

本人发现unsplash的速度较慢，希望作者添加其他源或支持添加其他源。

**Comment by stiekel** [comment]
抱歉，才看到你的 issue ，可以参见这里的配置 [背景图来源的配置](https://github.com/stiekel/hexo-theme-random/blob/master/README.CN.md#背景图来源的配置) 。
