### ISSUE TITLE
默认的代码高亮不是很好看，希望能改一下.

### ISSUE THREAD

**Issue by GoingMyWay** [stiekel/hexo-theme-random#45]
你好，我使用了你开发的主题，但是发现代码高亮部分默认的结果不是很好看，附上一个链接：http://goingmyway.cn/2017/07/14/Understanding-Session-and-Graph/

**Comment by stiekel** [comment]
的确不好看。可能是主题 css 里调整过的样式影响了代码高亮。

**Comment by GoingMyWay** [comment]
@stiekel 请问我应该怎么改？

**Comment by stiekel** [comment]
@GoingMyWay 是主题的问题，我这周找时间把 问题解决掉。

**Comment by GoingMyWay** [comment]
@stiekel 谢谢。

**Comment by HowinLoo** [comment]
你好请问你的代码块是怎样做到的，我为什么缩进没有行号，缩进效果也不是我想要的

**Comment by GoingMyWay** [comment]
@stiekel 请问您更新了代码了吗

**Comment by stiekel** [comment]
@GoingMyWay  抱歉，暂时没有。

**Comment by GoingMyWay** [comment]
@HowinLoo 估计你需要把#号去掉。最近我的一篇博客弄出来也不好看
 http://goingmyway.cn/2018/01/15/LeetCode-37-Sudoku-Solver/

**Comment by stiekel** [comment]
@GoingMyWay 你提出的代码与行号对不齐的问题，已经解决了。
@HowinLoo 我不确定你是如何组织代码块的，你可以按照这个[示例](https://github.com/stiekel/random-demo/blob/master/source/_posts/tag-plugins.md#scritps) 来组织。

**Comment by GoingMyWay** [comment]
@stiekel 谢谢，但是更新代码之后并且重新hexo g之后还是有问题，比如  http://123.207.82.155/2018/01/15/LeetCode-37-Sudoku-Solver/。不知道是不是我的使用出现了问题。
