### ISSUE TITLE
markdown [TOC]  目录不生效

### ISSUE THREAD

**Issue by gaojindeng** [stiekel/hexo-theme-random#47]
如标题

**Comment by gaojindeng** [comment]
目录，没法显示呀！博主有空能解决下不？

**Comment by stiekel** [comment]
@gaojindeng 能否给一下斧 md 文件。我这边好像是没有问题的。
像这个[文章](http://chensd.com/2017-12/2017-my-technology-logs.html)，[源码](https://raw.githubusercontent.com/stiekel/blog/master/source/_posts/2017-my-technology-logs.md)，都是可以的。
