### ISSUE TITLE
LaTeX显示问题

### ISSUE THREAD

**Issue by GoingMyWay** [stiekel/hexo-theme-random#49]
你好，非常感谢你能开发这个主题免费给大家用，最近打算在写LaTeX，按照这篇文章的步骤：http://blog.csdn.net/emptyset110/article/details/50123231 , 但是发现当前的主题好像不支持。请问当前的主题支持LaTeX的公式显示吗？

**Comment by stiekel** [comment]
@GoingMyWay 不好意思，这个没有测试过。

**Comment by Baileyswu** [comment]
经过我的修改可以完美支持公式了🤭
看我[blog](https://baileyswu.github.io/tags/mathjax/)

**Comment by Baileyswu** [comment]
检查几个方面吧
比如在引用代码前的```里有没有声明是cpp，因为不同语言的高亮选项不一样
然后检查一下你的escape和em的正则表达式是否是正确的，位置在 node_modules/kramed/lib/rules/inline.js

**Comment by Baileyswu** [comment]
Latex的公式支持，可以到我repository下载一下，然后在[这里](https://baileyswu.github.io/2018/09/test-equation/)有一些说明

**Comment by GoingMyWay** [comment]
> 检查几个方面吧
> 比如在引用代码前的```里有没有声明是cpp，因为不同语言的高亮选项不一样
> 然后检查一下你的escape和em的正则表达式是否是正确的，位置在 node_modules/kramed/lib/rules/inline.js

现在公式可以显示了，谢谢！

我在```后面加了cpp，但是还是会这样。`node_modules/kramed/lib/rules/inline.js`我用的是你的博客中的代码。

**Comment by GoingMyWay** [comment]
> Latex的公式支持，可以到我[repository](https://github.com/Baileyswu/hexo-theme-random)下载一下，然后在[这里](https://baileyswu.github.io/2018/09/test-equation/)有一些说明

https://baileyswu.github.io/archives/  你好，archives的博客的排序出现了问题。

**Comment by Baileyswu** [comment]
我也发现了这个问题，正在解决中 @stiekel 请问site.post里的内容在哪里生成和排序的呀

**Comment by stiekel** [comment]
@Baileyswu site.post 是 hexo 提供的变量。
