### ISSUE TITLE
404 not found problem

### ISSUE THREAD

**Issue by JohnnyZhunan** [stiekel/hexo-theme-random#50]
Recently, I have download your hexo-theme-random as my personal Blog's theme , but when I click categories, about, and tags,  it show me "404 page not found", My github repository is 
https://github.com/JohnnyZhunan/JohnnyZhunan.github.io

**Comment by stiekel** [comment]
You need to create those pages, https://github.com/stiekel/hexo-theme-random#create-tags-list-page-and-categories-list-page
