### ISSUE TITLE
代码段中出现单行注释，剩余代码高亮设置失效

### ISSUE THREAD

**Issue by prosscode** [stiekel/hexo-theme-random#52]
代码段中某一个地方出现单行注释，那么注释下面的代码只剩下一种颜色了，高亮设置失效。
详见：https://prosscode.github.io/2018/HDFS%E6%A0%B8%E5%BF%83API%E7%BC%96%E7%A8%8B%E6%A1%88%E4%BE%8B/
求解决。

**Comment by stiekel** [comment]
好，我最近看看。

**Comment by liuyuqi21** [comment]
请问还没解决吗

**Comment by stiekel** [comment]
@liuyuqi21 已经修复。参见这个 [Demo](https://env-wwufiyop-1252212664.tcloudbaseapp.com/random-demo/2018/04/13/Source-code/)。

**Comment by liuyuqi21** [comment]
> @liuyuqi21 已经修复。参见这个 [Demo](https://env-wwufiyop-1252212664.tcloudbaseapp.com/random-demo/2018/04/13/Source-code/)。

好嘞，谢谢
