### ISSUE TITLE
添加hexo-translate-title

### ISSUE THREAD

**Issue by prosscode** [stiekel/hexo-theme-random#53]
荣幸使用random模板，
最近我注意到了文章的url地址中出现中文字符，复制出去会自动替换为utf-8编码显示，
是否添加开启hexo-translate-title或关闭hexo-translate-title的功能。
谢谢！

**Comment by stiekel** [comment]
@prosscode 我最近看看文件，来把这个加了试试。

**Comment by stiekel** [comment]
@prosscode 刚刚我看了一下 [hexo-translate-titile](https://www.npmjs.com/package/hexo-translate-title) 的文档，发现可以自己在站点中配置，要不这个功能就不加入到主题中了。一是与主题本身关系不大，二是配置其实还是有一定门坎。
