### ISSUE TITLE
归档只能显示10篇文章，请问如何修改显示数目

### ISSUE THREAD

**Issue by Snailclimb** [stiekel/hexo-theme-random#55]
归档只能显示10篇文章，请问如何修改显示数目

**Comment by DiDongDongDi** [comment]
同问

**Comment by AlanHaze** [comment]
![_20180817105837](https://user-images.githubusercontent.com/37692803/44245703-a49f2300-a20c-11e8-9070-4822038999a3.png)
10改为0即可

**Comment by Baileyswu** [comment]
hexo-theme-random-master/layout/includes/recent-posts.swig 
两处
```for postItem in page.posts.toArray()```
改为
```for postItem in site.posts.toArray()```
应该是作者写的bug

**Comment by stiekel** [comment]
@Baileyswu Random 没有做翻页，归档页面，是显示所有文章列表。参见[这里](http://chensd.com/archives/)。

**Comment by xlindo** [comment]
> @Baileyswu Random 没有做翻页，归档页面，是显示所有文章列表。参见[这里](http://chensd.com/archives/)。

我更新了，但是是乱的啊，不能按年归档

**Comment by stiekel** [comment]
@xlindo 你是说哪个页面是乱的？存档页？

**Comment by xlindo** [comment]
> @xlindo 你是说哪个页面是乱的？存档页？

![_20181209083250](https://user-images.githubusercontent.com/8579640/49694559-e6bded00-fb8c-11e8-8e56-8a448a72bda3.png)
archives

**Comment by stiekel** [comment]
@xlindo 33 个没有显示完吗？

**Comment by stiekel** [comment]
@xlindo 奇怪，我这好像也没有这种情况，要不你把主题重新 clone 一下？

**Comment by xlindo** [comment]
> @xlindo 奇怪，我这好像也没有这种情况，要不你把主题重新 clone 一下？

试过了，不行，可能是个例吧，谢谢

**Comment by stiekel** [comment]
@xlindo 你把 hexo 根目录中的数据文件删除了重新生成试试。
