### ISSUE TITLE
random主题写博客插入图片问题

### ISSUE THREAD

**Issue by SmallRedSister** [stiekel/hexo-theme-random#56]
作者使用swig写样式真的很6，请教一下写博客如何插入图片；其实之前我在网上看了很多大家的方法，毕竟大家使用的hexo主题不一样，主题实现语言各不一样。如果我想添加一个相册，可以给我 一些建议吗？

**Comment by AlanHaze** [comment]
![image](https://user-images.githubusercontent.com/37692803/44327571-9877c780-a491-11e8-9443-9f3b46b802bb.png)
语法如上，如果不想用付费图床的话用微博相册就很好（我就是），不想该相册影响自己微博的话权限设为私密就行

**Comment by AlanHaze** [comment]
![_20180820155611](https://user-images.githubusercontent.com/37692803/44327697-f2788d00-a491-11e8-8432-855933c27f96.png)
语法如上，如果不想用付费图床的话用微博相册就很好（我就是），不想该相册影响自己微博的话权限设为私密就行
