### ISSUE TITLE
在文章中插入表格只显示表格内容不显示表格框线

### ISSUE THREAD

**Issue by AlanHaze** [stiekel/hexo-theme-random#58]
表格语法如下：
![_20180817105837](https://user-images.githubusercontent.com/37692803/44245807-550d2700-a20d-11e8-8dbe-97c16bcc7552.png)
上传至Github结果如下：
![_20180817110257](https://user-images.githubusercontent.com/37692803/44245818-61917f80-a20d-11e8-939a-5a9c8f0f7aaf.png)
 只剩下表格内容，无任何框线
我用的Markdown编辑器如下：
![_20180817110402](https://user-images.githubusercontent.com/37692803/44245836-81c13e80-a20d-11e8-9339-05c3ef9720c8.png)

**Comment by stiekel** [comment]
我没有测试表格的样式，你说的问题应该是存在的。你的表格语法没有问题。
