### ISSUE TITLE
uyan已经倒闭很久了，能否更新下第三方评论系统

### ISSUE THREAD

**Issue by troycizion123** [stiekel/hexo-theme-random#61]
uyan已经倒闭很久了，能否更新下第三方评论系统
laibili，valin的代码可否添加下。
谢谢

**Comment by gouheng** [comment]
https://valine.js.org

**Comment by Baileyswu** [comment]
#64 I've added valine in this PR

**Comment by stiekel** [comment]
thanks @Baileyswu for new valine comment supports.
