### ISSUE TITLE
代码块的css在哪里优化？

### ISSUE THREAD

**Issue by tripleday** [stiekel/hexo-theme-random#7]
总觉得每篇博客里的代码行号和代码本身离得特别近，少了一点美观，求教在哪个css里？

**Comment by stiekel** [comment]
哈哈，我也有这个感觉。代码块这块儿，我这周会优化一下。
代码块主题中没有专门优化，是hexo自动生成的。可以用chrome开发人员工具看一下代码块的结构和class，再做针对性样式调整。

谢谢你的建议。

**Comment by stiekel** [comment]
应该就是调整一下 `table` 中 `gutter` 列与 `code` 列之间的间距就行了

![theme code highlight](http://two.yt/images/2016/06/12/qx9A.png)

**Comment by stiekel** [comment]
代码块的显示已经修改了：
* 修改了左右上下的边距
* 修改了行号列与代码列的间隔

具体参见提交 38c31f38150be16c60cbd1bb084bd07ed9d030ce 。如果你要自定义修改，可以在[这里添加](https://github.com/stiekel/hexo-theme-random/blob/master/source/css/random.styl#L540-L544)。

**Comment by tripleday** [comment]
谢谢你耐心的解答，膜拜一发大神。这个主题真心很棒！

**Comment by stiekel** [comment]
@tripleday 哈哈，喜欢就好。
