### ISSUE TITLE
渲染出错

### ISSUE THREAD

**Issue by imlisiran** [stiekel/hexo-theme-random#70]
<img width="697" alt="屏幕截图 2022-10-08 170051" src="https://user-images.githubusercontent.com/110017885/194699447-ee98e442-f61f-487d-a83c-18740d358404.png">
怎么解决？

**Comment by zhiyuan5986** [comment]
我也是这样，请问您是怎么解决的呢？

**Comment by imlisiran** [comment]
不知道哈

在 2022年10月20日星期四，zhiyuan5986 ***@***.***> 写道：

**Comment by imlisiran** [comment]
我也没解决

在 2022年10月20日星期四，zhiyuan5986 ***@***.***> 写道：

**Comment by zhiyuan5986** [comment]
估计是很久没维护了，渲染有问题。

**Comment by stiekel** [comment]
@zhiyuan5986 @imlisiran 是不是没有安装 swig 依赖？

**Comment by zhiyuan5986** [comment]
> @zhiyuan5986 @imlisiran 是不是没有安装 swig 依赖？

刚刚在win10本地安装了swig，加到环境变量中了，再次尝试，还是没有用哎。谢谢lz。

**Comment by zhiyuan5986** [comment]
有用了，原因是hexo在5.0之后把swig给删除了需要自己手动安装，从[https://blog.csdn.net/qq_39898645/article/details/109181736](https://blog.csdn.net/qq_39898645/article/details/109181736)看到的，谢谢lz和小伙伴。

`npm i hexo-renderer-swig`

**Comment by stiekel** [comment]
> 有用了，原因是hexo在5.0之后把swig给删除了需要自己手动安装，从https://blog.csdn.net/qq_39898645/article/details/109181736看到的，谢谢lz和小伙伴。
> 
> `npm i hexo-renderer-swig`

hexo 变化这么大的吗，看来要找时间把这个模板语言换掉了。
