### ISSUE TITLE
统计和分享评论功能

### ISSUE THREAD

**Issue by yizuochengchi** [stiekel/hexo-theme-random#9]
你好 请问 统计和分享评论功能具体怎么实现？谢谢！

**Comment by stiekel** [comment]
统计支持百度统计和 Google Analytics ，评论支持多说、友言、Disqus。
先申请账号，然后把 id 或者  key 一类，在 Hexo 主配置文件或者主题配置文件中，具体配置请[参见文档](https://github.com/stiekel/hexo-theme-random/blob/master/README.CN.md#第三方服务的配置)。

**Comment by stiekel** [comment]
也可以参考这里：

* [统计配置](https://github.com/stiekel/blog/blob/master/_config.yml#L116-L117)
